### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by mpejcoch** [metno/MMS#3]
Create user documentation in form of cht.sh

**Comment by mpejcoch** [comment]
Split README.md in https://github.com/metno/MMS into more files. Enable Github pages for a simple clean view of the user documentation. Write a couple of lines for cht.sh

**Comment by mpejcoch** [comment]
Check if it's possible to render Markdown in the terminal.

**Comment by johtoblan** [comment]
Document usage of work dir
