### ISSUE TITLE
Quantify non-functional requirements

### ISSUE THREAD

**Issue by johtoblan** [metno/MMS#43]
Need to figure out how many datasets being sent through the Event Queue

Trygve will find out about
- data from Observation department
Johannes will find out about
- Data from SUV (modeldata)
- Hav og Is?
Charlie will find out about
- Data from FOU-KL

These metrics shall be added to the data management architecture document on gitlab.

**Comment by TAlonglong** [comment]
Satellite data: less than 100 per day
Radardata: less than 1000 per day
Radiosondes, ceilometers, ducting etc: approx 37000 per day
Assume HF-radar less than 100 per day
Observation: this varies from 24/day to 1500000/day depending on what update frequency we want.
ecf-prod: Currently 4432 message/day   * 2 (For A and B datacenters)

**Comment by charlienegri** [comment]
from FoU-KL the candidate dataset that can be most easily contributed to the queue + catalog is basically the uemep runs,   
so depending on how we define that "dataset" (i.e. at which level we decide to attach the metadata), it could be 4 datasets per day, or if we have to send every produced file as separate dataset, it's 4x1864 per day

**Comment by mortenwh** [comment]
merged in gitlab
